version: 0.1

phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
      - echo Amazon ECR
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - IMAGE_URI=${REPOSITORY_URI}:${TAG}
      - echo $TAG
      - echo $IMAGE_URI