spring:
  datasource:
    url: jdbc:postgresql://springbootaws.caypsfgamslz.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: DQJXwi0ON14PN7CI1hr6
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true

cloud:
  aws:
    s3:
      avatarBucket: "sba-avatar"
    sqs:
      emailQueue: email
    ses:
      atendimento: atendimento@bitrus.com.br
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      access-key: AKIA4X7EGBZUSUQE3WFP
      secret-key: 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
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/876115005033/email

