spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    secretName: dev/sba-db/postgres
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true

cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false

